apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus
spec:
  ports:
    - port: 8080
      targetPort: 9090
      nodePort: 32700
  selector:
    app: prometheus
  type: NodePort

