apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "500M"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
        - name: data-mount
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: false
      volumes:
      - name: data
        emptyDir: {}
      - name: data-mount
        configMap:
              defaultMode: 420
              name: grafana-datasources
